### ISSUE TITLE
ModuleNotFoundError: No module named 'slycot'

### ISSUE THREAD

**Issue by Ehsan-Home** [mpkuse/inverted_pendulum#1]
Hi. Thank you for your cool src of code.  

I have a problem with running  _controlled_cart_and_pendulum.py_.

When I try to run through
`python controlled_cart_and_pendulum.py`

I get the following error:

`Traceback (most recent call last):
  File "C:\Users\...\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\control\statefbk.py", line 389, in lqr
    from slycot import sb02md
ModuleNotFoundError: No module named 'slycot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "controlled_cart_and_pendulum.py", line 51, in <module>
    K, S, E = control.lqr( ss.A, ss.B, Q, R )
  File "C:\Users\...\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\control\statefbk.py", line 392, in lqr
    raise ControlSlycot("can't find slycot module 'sb02md' or 'sb02nt'")
control.exception.ControlSlycot: can't find slycot module 'sb02md' or 'sb02nt'`

Any help is highly appreciated.

Thanks!

**Comment by mpkuse** [comment]
I see that you are running it on windows. I am not sure how to fix it, but looks like the python control package is the issue. I recommend you try to run some sample codes from control package on your system first.
